### PR TITLE
Add proposed solution in order to send custom dimensions and metrics as ...

### PR DESCRIPTION
**Pull request by cavi21**
Hi there @tpitale! I'm proposing this pull request in order to be able to add **[Custom Dimensions](https://developers.google.com/analytics/devguides/platform/customdimsmets)** and **[Custom Metrics](https://developers.google.com/analytics/devguides/platform/customdimsmets)** to the **Product scope**.

As [Google Documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#pr_cd_) shows, I'm adding the ability to pass to the **Product Measurement** two more parameters with an array in each of them, so in the [Staccato::Measurement::Product](https://github.com/goodpeople/staccato/blob/add_custom_dimension_and_metrics_to_product/lib/staccato/measurement/product.rb#L18) Class I'm adding those to the **FIELDS**:
```ruby
      FIELDS = {
        ...
        ...
        position: 'ps', # integer
        custom_dimensions: 'cd', # array[ array[ index, text ] ]
        custom_metrics: 'cm' # array[ array[ index, integer/currency] ]
      }.freeze
```

And because of those values that are arrays in order to handle 1-200 indexes possibilities I need to propose another logic to the **[#params](https://github.com/goodpeople/staccato/blob/add_custom_dimension_and_metrics_to_product/lib/staccato/measurable.rb#L33)** method of the [Measurable Class](https://github.com/tpitale/staccato/blob/master/lib/staccato/measurable.rb)

I also add the test to show the use of it.

Do you have any opinion or concern about it that maybe I missed?

Thanks a lot for the time!
Cheers and nice friday!

### CODE REVIEW

**Comment by tpitale** [comment]
There appear to be 3 places that custom dimensions/metrics can be set. I was aiming to solve them all at once by use of `add_custom_dimension` and `add_custom_metric` as I already do in the `Hit` module.

Can you tell me a bit more about your choice of an Array of Arrays as the interface for setting these custom dimensions/metrics?

**Comment by tpitale** [comment]
Thanks for all the measurment => measurement fixes in the specs. I'm gonna make that change in a distinct commit, so you don't have to have that in your PR.

**Comment by tpitale** [comment]
Just for clarity, this was the interface I was planning to add to both Product and ProductImpression: https://github.com/tpitale/staccato#custom-dimensions-and-metrics

**Comment by cavi21** [comment]
Hey there! @tpitale thanks for the review and comments. 

I was aware in the interface that you are using when sending the Custom Dimensions and Metrics for hits, but I thought in the Array of Arrays because of the way they need to be attached to each object (in this case the product), also to keep the logic in one place, but happy to see other ideas... 

How you were imaging adding this features following you type of interface? happy to move forward on that direction on this **Product** and the other 2 places in which they can be attached.

**Comment by cavi21** [comment]
Also I think that because how the way are the [Measurements](https://github.com/tpitale/staccato#additional-measurements) are handle it's different that the actual **Action** like the **pageview**, that's why you are adding a measurement to them with `pageview.add_measurement` for instance.

The measurements also have an index itself, so are you thinking to add the custom data with something like this for example?
```ruby
pageview.add_custom_dimension_to_measurement(:product,  {
  index: 1,
  dimension_index: 1,
  value: 'value_for_dimension'
})
```
I feel it like too verbose and feel somehow impractical, don't you think? open to clear my mind and see new approaches thought! :pray: :smiley:

**Comment by tpitale** [comment]
I was thinking of having `add_measurement` accept an instance of a `Measurable` (as an alternative to a hash). Something like this: 

```ruby
product = Staccato::Measurement::Product.new(some_attributes)
product.add_custom_dimension(1, 'baseball')

pageview.add_measurement(:product, product)
```

The Array of Arrays only has me worried because it lacks supporting structure. We can change the internal implementation of `add_custom_dimension` without users having to change their code. With an Array of Arrays, we lose some of that ability.

**Comment by cavi21** [comment]
Ahh ok I see what you have in mind and also like the approach. I have one more last question though, is there a real need to give structure? or are you aware of future changes?
Thanks!

**Comment by tpitale** [comment]
No specific changes that I'm aware of. I just know that Google has a history of changing their APIs (especially Google Analytics) frequently.

**Comment by cavi21** [comment]
Perfect then! I'm working on another branch in order to propose another pull request! thanks for all the time you took on this and replying. 

I'll close this and open a new one, let me know if you prefer another thing!
Cheers

**Pull request closed without merging**
