### PR TITLE
excon_adapter

### PR DESCRIPTION
**Pull request by rus-max**

### CODE REVIEW

**Comment by tpitale** [comment]
Excon is an http library supported by Faraday, which is one of the adapters Staccato already supports. https://github.com/lostisland/faraday#faraday

If you'd like to add examples to the readme for using excon with faraday I would find that helpful: https://github.com/tpitale/staccato#http-adapters

Thank you!

**Comment by rus-max** [comment]
When use Excon as default_adapter for Faraday it gives error 'stack level too deep'

**Comment by tpitale** [comment]
Ah, well that's a bug. Mind opening another issue and I will fix that?

**Comment by rus-max** [comment]
Thank you for gem. I'm satisfied with my decision

**Comment by tpitale** [comment]
@rus-max This is fixed in Staccato v0.4.6. The issue was using Faraday, with any faraday adapter.

**Pull request closed without merging**
