### PR TITLE
Add data_source as a global option

### PR DESCRIPTION
**Pull request by matt-thomson**
As specified here:

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ds

### CODE REVIEW

**Comment by tpitale** [comment]
Mind adding a note to the Readme about the options being 'web' or 'app'? Thanks!

**Comment by matt-thomson** [comment]
I think that this can take any value - the docs also show `call center` and `crm` as options.

**Comment by tpitale** [comment]
Sorry, let me clarify: it seems like web and app have meanings that folks might want to be aware of based on googles other tools. I was hoping for just a comment on that in the readme.

**Comment by matt-thomson** [comment]
Ah, understood - have updated with this change.

**Comment by matt-thomson** [comment]
Thanks Tony! Would it be possible to push a new release to Rubygems? Would be good to get back to tracking version numbers rather than commit hashes.

**Comment by tpitale** [comment]
Yep. I'll release shortly.

**Comment by tpitale** [comment]
Released 0.4.3.

**Comment by matt-thomson** [comment]
Fantastic, thank you!

**Pull request merged**
