### PR TITLE
Enhanced Ecommerce!

### LINKED ISSUE #23: Support for Enhanced Ecommerce Parameters
I was trying to figure out how to extend staccato to support refunds but am somewhat confused.

The refund docs are here:
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#enhancedecom

under "Measuring Refunds"

I was unclear how to create a class that would do the right thing. My first stab looked something like this

```ruby
      module Staccato
        class Refund
          include Staccato::Hit
          FIELDS = {
            transaction_id: 'ti',
          }

          def type
            :transaction # what goes here? how does stacatto know refunds vs purchases
          end
        end
      end
```

### PR DESCRIPTION
**Pull request by tpitale**
* Measurable module
* Measurements:
  1. checkout
  2. checkout_option
  3. impression_list
  4. product
  5. product_impression
  6. promotion
  7. transaction
* NullMeasurement
* Add measurement to a hit
* Spec coverage
* Fully updated docs
* README updates for all measurement classes

Resolve #23.

### CODE REVIEW

**Comment by comp615** [comment]
This looks really solid. Hope it gets merged!

**Comment by tpitale** [comment]
Just waiting for @skwp and @nadavshatz to try it out.

**Comment by skwp** [comment]
sorry we're not using staccato anymore

**Comment by skwp** [comment]
nevermind, we are :)

**Comment by nadavshatz** [comment]
I will probably test it sometime this week.

**Comment by tpitale** [comment]
Thanks!

**Comment by nadavshatz** [comment]
@tpitale looks like it's working great, if you can merge it and bump the version it would be great.

I'm gonna be using it so if any issues come up I'll make them known. I can keep using this branch for now but would prefer not to just incase it's removed and also to make sure it doesn't get stale.

**Comment by tpitale** [comment]
Yeah, as long as it's not crashing or anything crazy for you I'll merge and release a gem version.

**Comment by nadavshatz** [comment]
I only did a few tests by now but it seams fine. I don't use all features but I tried the ones that are relevant to me and the new stuff.

**Comment by tpitale** [comment]
@nadavshatz @skwp @comp615 I've released gem version 2.2.0. Enjoy!

**Comment by tpitale** [comment]
Correction: 0.2.0 whoops!

**Comment by nadavshatz** [comment]
Thanks!!

**Pull request merged**
