### PR TITLE
Adds an adapter to validate hits. It takes another adapter as its arg…

### PR DESCRIPTION
**Pull request by Tyler-Murphy**
…ument.

### CODE REVIEW

**Comment by tpitale** [comment]
Looks good, can you add to the README how to use it? Then I'll merge.

**Comment by Tyler-Murphy** [comment]
I don't have to time to update anything else right now, but usage is:

```
2.2.2 :004 > validator = Staccato.tracker('UA-3000737-39') { |config| config.adapter = Staccato::Adapter::Validate.new(Staccato::Adapter::Net::HTTP) }
 => #<Staccato::Tracker:0x007fbad3163bc8 @id="UA-3000737-39", @client_id=nil, @hit_defaults={}, @adapter=#<Staccato::Adapter::Validate:0x007fbad3163ba0 @adapter=#<Staccato::Adapter::Net::HTTP:0x007fbad31638d0 @uri=#<URI::HTTPS https://www.google-analytics.com/debug/collect>>>> 
2.2.2 :005 > validator.pageview(path: '/', hostname: 'example.com')
 => "{\n  \"hitParsingResult\": [ {\n    \"valid\": true,\n    \"parserMessage\": [ ],\n    \"hit\": \"POST /debug/collect HTTP/1.1\"\n  } ]\n}\n" 
2.2.2 :006 > puts validator.pageview(path: '/', hostname: 'example.com')
{
  "hitParsingResult": [ {
    "valid": true,
    "parserMessage": [ ],
    "hit": "POST /debug/collect HTTP/1.1"
  } ]
}
 => nil 
```

**Comment by tpitale** [comment]
Okay, I'll add it.

**Comment by tpitale** [comment]
https://github.com/tpitale/staccato/commit/2746c63de5e39999e9e1a754a78f89f2b2b941a8

**Pull request merged**
