### PR TITLE
Hit validation

### PR DESCRIPTION
**Pull request by Tyler-Murphy**
It might be nice to be able to validate hits, as described here:
https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits

See the example at the bottom of the readme for usage.

### CODE REVIEW

**Comment by tpitale** [comment]
This looks good. Mind adding some specs?

**Comment by tpitale** [comment]
@Tyler-Murphy do you have a spec for this?

**Comment by tpitale** [comment]
You can now accomplish this using configuration of an adapter. See PR #21.

**Comment by Tyler-Murphy** [comment]
Sorry for the non-responsiveness. The adapter method is much nicer! Thanks for the update.

**Comment by tpitale** [comment]
@Tyler-Murphy I would love to have Staccato include an adapter for this hit validation. Mind sending a PR for that?

**Pull request closed without merging**
