### PR TITLE
Assign request to a response variable in Net::HTTP adaptor

### PR DESCRIPTION
**Pull request by arturoherrero**
I'm having problems reading the events information in Google Analytics. After spend a few days testing, I figured out that if I assign the request to a response variable, it works!

I found this solution trying to read the information from the Google Analytics response and I saw that when I use a variable it's working all the time.

### CODE REVIEW

**Comment by tpitale** [comment]
That's … interesting. Any idea as to _why_ that's happening? Do you think Net::HTTP isn't actually making the request or something?

I have no problem merging this, but I'd really like to understand the why before I do.

**Comment by arturoherrero** [comment]
@tpitale same here, I don't understand if it's working for others.

I tried to use this gem with the Faraday adaptor (changing the default adaptor) and it's not working for me. I got the following error, but this is another story:
```
/Users/arturo/.rvm/gems/ruby-2.2.2/gems/foreman-0.60.2/lib/foreman/engine.rb:226:in `synchronize': can't be called from trap context (ThreadError)
```

**Comment by tpitale** [comment]
I think that is related to the version of faraday, possibly.

**Comment by arturoherrero** [comment]
@tpitale Do you have the change to test this? I like to have a new gem version with the latest features and this change, please.

**Comment by tpitale** [comment]
I don't see any tests. Did you push them up?

I have not been able to find any valid reason why assigning to a local variable would somehow fix this request.

All of my tracking is working. I suspect something else happened for your stats.

**Comment by arturoherrero** [comment]
I haven't write any test because the only way to test this it's going to the Google Analytics Dashboard and  see if you are receiving the data.

Based on my test this commit resolves the problem but I don't understand why it's not working without the assignment. Doesn't make sense for me.

I think that is a small thing to merge. Anyway I using my own fork in production, so if you like to close the pull request, just do it. If you merge I'll switch to the oficial gem.

Thanks!

**Comment by tpitale** [comment]
If someone else reports it being a problem, I'll merge. But, I think you were seeing some other problem.

**Comment by tpitale** [comment]
To quote @_m_b_j

> @tpitale Noop. Redunant AST for the same semantics. Mutant would take it out and all the specs in the world you can write cannot cover it

**Comment by mbj** [comment]
@tpitale On twitter my nick is `@_m_b_j_` here on GH its @mbj ;)

**Comment by tpitale** [comment]
@arturoherrero I've asked around … this code change is a no-op. Unless it happens to be a bad gem release or a fluke bug in ruby … this change doesn't actually change anything.

Would you mind just trying against master … I still see requests being made against a mock GA server.

**Comment by tpitale** [comment]
@mbj Thanks, updated my comment :-)

**Pull request closed without merging**
