### PR TITLE
add option to set read_timeout for Net::HTTP

### PR DESCRIPTION
**Pull request by grantspeelman**
* add option to set read_timeout for Net::HTTP
* also had to refactor how net::http gets stub in integration tests

### CODE REVIEW

**Comment by grantspeelman** [comment]
@tpitale Could this be consider to be merged in, I am happy to make adjustments.
one adjust could be is use webmock for the integration specs.

**Comment by tpitale** [comment]
I have another PR I'm working on for http adapters. I think it will be easier for you to use that feature, rather than adding it to Staccato. There are many, many options that may need passing to net/http or faraday, and it isn't really the tracker's concern. Thank you for your time and work on this, though!

**Comment by tpitale** [comment]
Take a look at #21. Once I merge that PR you can create your own adapter that implements the read timeout you want.

**Comment by grantspeelman** [comment]
Thanks, will give the new v0.3.0 a try

**Pull request closed without merging**
