### PR TITLE
Creates batch adapter with non thread

### PR DESCRIPTION
**Pull request by bots-business**
We already have PR - #58 by @tpitale
This PR based on that changes

Added non thread batch and thread batch. 

Why non thread?
Thread is not always good with big count of tracking events. It requires additional database connection in RoR app.

### CODE REVIEW

**Comment by tpitale** [comment]
Thank you for the PR! The wonderful thing about adapters is that you can write your own.

I don't believe this is something I would like to have in Staccato directly, especially as I haven't heard back from the original requester and have not merged the original batch adapter.

**Comment by bots-business** [comment]
Thank you for quick response.

This PR based on original requester PR. 
It have Batch adapter and ThreadBatch Adapter from original PR as child class

> I don't believe this is something I would like to have in Staccato directly

In Bots.Business we have above 50 million events per month. (Above 20 events per second)
So batch adapter strongly required. This increases the processing speed by 20 times

But Thread adapter is not good - because you cannot select one task with it something like delayed jobs or etc.

Please do not close this PR

**Comment by tpitale** [comment]
The PR is closed. You are welcome to use this adapter in your own code. Thank you.

**Comment by tpitale** [comment]
@bots-business please leave a comment on the existing PR if you have feature requests for it. I could see about updating it to not make the `flushing_thread` if no flushing timeout is provided (requires calling `clear` every time).

**Pull request closed without merging**
